### ISSUE TITLE
clicking twice at the same star = undefined

### ISSUE THREAD

**Issue by ghost** [dobtco/starrr#18]
In example:

When the star-rating is 5, and you click at the 5'th star again, the rating-value is undefined in the onchange.

`$('.starrr').starrr
({
  change: function(e, value){
    alert('new rating is ' + value) // First time all good, second time clicking the same star result is undefined
  }
})`

**Comment by ajb** [comment]
That is the intended behavior.

**Comment by ghost** [comment]
Wow, very quick reply! Why intended, undefined is not good. It should have a value of 5 again. How to get the value again without having a undefined?

**Comment by ajb** [comment]
It's how you clear the rating.

On Wed, Feb 24, 2016 at 8:31 AM, Silvester20 notifications@github.com
wrote:

> Wow, very quick reply! Why intended, undefined is not good. It should have
> a value of 5 again.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dobtco/starrr/issues/18#issuecomment-188256313.

## 

Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by ghost** [comment]
This is how I use your plugin:

When calling the plugin: `$('.rating').starrr({rating:<?php echo $value ?>});`
Then the onchange: `$('.rating_stars').on('starrr:change', function(e, value)`
When user confirm to give a new rating: `$(rating).starrr('syncRating', value);`

So in the onchange the "value" in `function(e, value)` is undefined after clicking the same star twice. Is there any possiblity to avoid this undefined and give the "value" the rating where it was called with
`<?php echo $value ?>` ?

**Comment by ghost** [comment]
Since I don't expect that you will fix this "intended" bug, for others just remove this line from the starrr.js.
`if (this.options.rating === rating) {
        rating = void 0;
      }`
