### ISSUE TITLE
Can we replace star images?

### ISSUE THREAD

**Issue by abdul-rehman** [dobtco/starrr#19]
Hi, i am new to Web Development. can anyone please tell if i can add my custom star image ? if No then there is any other way to do so?

**Comment by ajb** [comment]
Hi Abdul,

You should use CSS to customize the star image. You might want to customize the class name that gets added to make this easier:

### JS

``` js
$('.starrr').starrr({
  emptyClass: 'is_empty',
  fullClass: 'is_full'
})
```

### CSS

``` css
.starrr i.is_empty {
  // empty styles
}

.starrr i.is_full {
  // full styles
}
```

**Comment by abdul-rehman** [comment]
@ajb , Thanks a lot. it works!!!

**Comment by ajb** [comment]
Glad to hear. Best of luck!

On Fri, Mar 18, 2016 at 9:56 AM, Abdul Rehman notifications@github.com
wrote:

> @ajb https://github.com/ajb , Thanks a lot. it works!!!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/dobtco/starrr/issues/19#issuecomment-198372779

## 

Adam Becker
(951) 9-BECKER
@AdamJacobBecker
