### ISSUE TITLE
Keyboard support and half star rating

### ISSUE THREAD

**Issue by MrUzu** [dobtco/starrr#20]
Hi there!

Thanks for your nice code.

Is there any chance you would add a keyboard support : tabulation and space bar ?

And secondly, any chance the code may work for intermediate rate levels (half star or even less) : 1.5, 2.5?

Thanks in advance for your reading.

**Comment by ajb** [comment]
Keyboard support is a great suggestion! I'll release it as 2.0.0.

As for half-star rating, I guess I'd accept a PR but I have no real use for this myself.

**Comment by ajb** [comment]
Actually, maybe half-star would be better in a fork. One of the main selling points of this library is that it's small and focused.

**Comment by MrUzu** [comment]
Great thank you :)
