### ISSUE TITLE
How to initialize multiple star ratings

### ISSUE THREAD

**Issue by bruno-farias** [dobtco/starrr#23]
I'am trying to use this plugin into a simple comment system, more then one user can leave ratings of a product, so I must initialize several star ratings with its own rating value, until now I have done the following code:

``` javascript
$('.stars-users').starrr({
    readOnly: true,
    rating: $(this).data('rating')
});
```

Can anybody give me a help?

Thanks!

**Comment by jrobinsonc** [comment]
Try this:

``` javascript
$.each($('.stars-users'), function(){

    var $self = $(this);

    $self.starrr({
        readOnly: true,
        rating: $self.data('rating')
    });

});
```

**Comment by ajb** [comment]
Thanks @jrobinsonc.

**Comment by bruno-farias** [comment]
Thanks!
