### ISSUE TITLE
How to get starrr rating in JQuery?

### ISSUE THREAD

**Issue by gogoganta** [dobtco/starrr#32]
If the setter works this way in JQuery:
`$("#starrr_gf_"+id).starrr('setRating', 0);`
What about the getter?

**Comment by drusepth** [comment]
Looks like accessing the internal `getRating` function through `starrr` isn't returning a rating for the field.

However, you can get the current rating through the `options` hash with

    $("#starrr_gf_"+id).data('starrr').options.rating

Does that work for you?

**Comment by gogoganta** [comment]
Yes that's it! Thank you so much!
