### ISSUE TITLE
How to re-initialize the rating?

### ISSUE THREAD

**Issue by pierresh** [dobtco/starrr#5]
Hello,

Thanks a lot for your very efficient plugin. Nevertheless, I met an issue: in my project, end-users could use this rating function several times in the same page. Ideally the value of starrr would be re-initialized each time an item is evaluated but it is not, so end-users always see the previous rating. I tried the following line $('.starrr').data('rating',0); but this does not work. Is there any way to re-initialize the value of starr ?

Thanks,

Pierre

**Comment by ajb** [comment]
Hi,

You want `$(element).starrr('setRating', 0)`.

**Comment by pierresh** [comment]
Great, thanks a lot for your prompt feedback!

**Comment by pierresh** [comment]
Hello, 

is it possible to re-initialize the value of starr without triggering the event starrr:change ?

Thanks!

**Comment by rickysullivan** [comment]
`$(element).starrr('syncRating', 4)`

**Comment by pierresh** [comment]
Thanks for your feedback but this does not work... However I am using the latest release of starrr

**Comment by rickysullivan** [comment]
Can you create a jsFiddle with your code?

**Comment by rickysullivan** [comment]
http://jsfiddle.net/tvwtcf6q/1/
