### ISSUE TITLE
hover event?

### ISSUE THREAD

**Issue by rubytastic** [dobtco/starrr#7]
First off, 
Amazing little star rating plugin. 
Thank you for creating it!

Would like to add a hover event so that if you hover above star 1,2,3,4,5 the value is send back to the browser so you could do an alert. Just like the regular click star -> alert. But then on hover. 
Is this hard to add ? Im not a jquery coder myself but will try to digg your code a bit more to see where I could come up with.

I suggest removing the font-size 16px on the .starrr i element so you can use fa-2x to have bigger icons also.

**Comment by ajb** [comment]
``` js
$(document).on('mouseover', '.starrr i', function(){
var num = $(this).closest('.starrr').find('i').index($(this)) + 1;
console.log(num);
})
```

**Comment by rubytastic** [comment]
Thank you ajb, figured out some solution also in the same category as yours
the plugin works great!
